version: '3.4'
networks:
    sqlnetwork:
        external: true
services:
  chatappbackend:
    container_name: chat-app-be
    image: midouz/chatappbackend
    user: root
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ChatAppBackEnd/Dockerfile
    ports:
        - 8081:80
        - 8080:443
    environment:
        ASPNETCORE_URLS: https://+;http://+
        ASPNETCORE_HTTPS_PORT: 443
        DB_HOST: mysql

        #DB_HOST: 172.17.0.1,1433
        DB_NAME: ChatApp
        DB_SA_PASSWORD: MySecretPassword@123
        ASPNETCORE_Kestrel__Certificates__Default__Password: "ducphuong198"
        ASPNETCORE_Kestrel__Certificates__Default__Path: /https/midouz.online.pfx
    #depends_on:
    #    - chatappdb
    networks:
        - sqlnetwork
    extra_hosts:
        - host.docker.internal:host-gateway

  #chatappdb:
  #  container_name: chat-app-db
  #  image: mcr.microsoft.com/mssql/server:2019-latest
  #  environment:
  #      accept_eula: y
  #      mssql_sa_password: MySecretPassword@123
  #  ports:
  #      - 1434:1434
  #  networks:
  #      - chatapp
            #image: ${DOCKER_REGISTRY-}chatappbackend
            #image: midouz/chatappbackend