version: '3.4'
networks:
    chatapp:
services:
  chatappbackend:
    container_name: chat-app-be
    image: midouz/chatappbackend
    user: root
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: ChatAppBackEnd/Dockerfile
    ports:
        - 8081:80
        - 8080:443
    environment:
        ASPNETCORE_URLS: https://+;http://+
        ASPNETCORE_HTTPS_PORT: 443
        DB_HOST: chatappdb
        DB_NAME: ChatApp
        DB_SA_PASSWORD: DB@Password
        ASPNETCORE_Kestrel__Certificates__Default__Password: "ducphuong198"
        ASPNETCORE_Kestrel__Certificates__Default__Path: /https/midouz.online.pfx
    depends_on:
        - chatappdb
    networks:
        - chatapp
    extra_hosts:
        - host.docker.internal:host-gateway

  chatappdb:
    container_name: chat-app-db
    tty: true 
    stdin_open: true
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=DB@Password
    ports:
        - 1433:1433
    networks:
        - chatapp

            #image: ${DOCKER_REGISTRY-}chatappbackend